PostgreSQL:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - DB_NAME=phonebook
    command: "--wal_keep_segments=32 --logging_collector=off"
    volumes:
      - postgresql:/d/docker/_data/postgresql